quarkus:
    hibernate-orm:
        database:
            generation: update
    http:
        port: 8082
    datasource:
        db-kind: mysql
        jdbc:
            url: jdbc:mysql://localhost:3306/prueb0a?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            driver : com.mysql.cj.jdbc.Driver
        username: root
        password: Fmoreirag15@